version: '3.8'

services:
  app:
    build: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pathfinder
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pathfinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
