spring:
  datasource:
    # url: jdbc:postgresql://ep-dry-water-a1yslt0i.ap-southeast-1.aws.neon.tech/pathfinder?user=pathfinder_owner&password=RkTVY3EmQJ6h&sslmode=require
    url: jdbc:postgresql://localhost:5432/pathfinder
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR