# Common configurations (shared between all profiles)
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org:
      apache.http: debug
      springframework:
        web: DEBUG
      hibernate: ERROR

# Profile-specific configurations
---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/pathfinder
    username: postgres
    password: postgres

#recombee:
#  private-token: ui0bb5rWDix4IUaQQAr6PzWqeddguXPXIclHuyLMYarPH2n85aturUXh76C0NRvk
#  database-id: pathfinder-dev
#
#mailgun:
#  api-key: 2c9117ed3960408e855767a23c6e3563-2b755df8-02d6f02b
#  domain: mg.pathphindr.com
zoom:
  oauth2:
    api-url: https://api.zoom.us

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

recombee:
  private-token: ${RECOMBEE_PRIVATE_TOKEN}
  database-id: ${RECOMBEE_DATABASE_ID}

zoom:
  client-id: ${ZOOM_CLIENT_ID}
  client-secret: ${ZOOM_CLIENT_SECRET}
  issuer: ${ZOOM_ISSUER}
  api-url: https://api.zoom.us

mailgun:
  api-key: ${MAILGUN_API_KEY}
  domain: ${MAILGUN_DOMAIN}

openai:
  groq-api-key: ${GROQ_API_KEY}