spring:
  datasource:
    # local dev without docker.
    #    url: jdbc:postgresql://localhost:5432/pathfinder
    #    username: postgres
    #    password: postgres

    # docker-compose
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

recombee:
  private-token: ${RECOMBEE_PRIVATE_TOKEN}
  database-id: ${RECOMBEE_DATABASE_ID}